# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Backend Deploy"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  version:
    name: "Calculate Version"
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.gitversion.outputs.major }}
      minor: ${{ steps.gitversion.outputs.minor }}
      patch: ${{ steps.gitversion.outputs.patch }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Install .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.x'
      - name: "Install GitVersion"
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.12.0'
          includePrerelease: true
      - name: "Determine Version"
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
  docker:
    name: "Docker build and deploy"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Backend/Dockerfile
          cache-from: |
            type=gha
          cache-to: |
            type=gha
          tags: kurza/sm7-personal-project-backend:latest,kurza/sm7-personal-project-backend:${{ needs.version.outputs.major }}.${{ needs.version.outputs.minor }}.${{ needs.version.outputs.patch }},kurza/sm7-personal-project-backend:${{ needs.version.outputs.major }}.${{ needs.version.outputs.minor }},kurza/sm7-personal-project-backend:${{ needs.version.outputs.major }}
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK }}
          webhook_secret: " "


